apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: default
type: Opaque
stringData:
  DB_ROOT_PASSWORD: "sarmale123"
  CONNECTION_STRING: "Server=mysql-service;Database=p15demo;User=root;Password=sarmale123;"